zdlra/models.py
"""Zdlra app models"""
from django.db import models
from django.urls import reverse

from core.models import Metric, Snapshot
from database.models.database.oracle import OracleDatabase


class Zdlra(models.Model):
    """Zdlra model"""

    name = models.CharField('Name', max_length=128)
    snapshot = models.ForeignKey(Snapshot, on_delete=models.CASCADE)

    class Meta:
        ordering = ['name']
        constraints = [
            models.UniqueConstraint(
                fields=['name'], name='zdlra_set_unique')
        ]

    def __str__(self):
        return f"{self.name}"

    def get_absolute_url(self):
        """Return object absolute url"""

        return reverse('zdlra:zdlra-detail', kwargs={'pk': self.pk})


class ZdlraSpaceMetric(Metric):
    """Zdlra space metric"""

    zdlra = models.ForeignKey(Zdlra, on_delete=models.CASCADE)
    size = models.PositiveIntegerField('Size')
    used = models.PositiveIntegerField('Used')

    class Meta(Metric.Meta):
        db_table = 'zdlra_zdlra_space_metric'

class ZdlraProtectionPolicy(models.Model):
    """Zdlra protection policy model"""

    name = models.CharField('Name', max_length=128)
    recovery_window_goal = models.DurationField('Recovery window goal')

    zdlra = models.ForeignKey(Zdlra, on_delete=models.CASCADE)

    class Meta:
        db_table = 'zdlra_zdlra_protection_policy'
        ordering = ['name']
        constraints = [
            models.UniqueConstraint(
                fields=['name', 'zdlra'], name='zdlraprotectionpolicy_set_unique')
        ]

    def __str__(self):
        return f"{self.name} ({self.recovery_window_goal}) on {self.zdlra}"

    def get_absolute_url(self):
        """Return object absolute url"""

        return reverse('zdlra:zdlraprotectionpolicy-detail', kwargs={'pk': self.pk})


class ZdlraDatabase(models.Model):
    """Zdlra database model"""

    state = models.CharField('State', max_length=12)
    creation_time = models.DateTimeField('Creation time')
    nzdl_active = models.CharField('Realtime redolog transport active', max_length=3)

    zdlra = models.ForeignKey(Zdlra, on_delete=models.CASCADE)
    protection_policy = models.ForeignKey(ZdlraProtectionPolicy, on_delete=models.CASCADE)
    snapshot = models.ForeignKey(Snapshot, on_delete=models.CASCADE)
    database = models.ForeignKey(OracleDatabase, on_delete=models.CASCADE)

    class Meta:
        db_table = 'zdlra_zdlra_database'
        ordering = ['database']
        constraints = [
            models.UniqueConstraint(
                fields=['database', 'zdlra'], name='zdlradatabase_set_unique')
        ]

    def __str__(self):
        return f"{self.database}"

    def get_absolute_url(self):
        """Return object absolute url"""

        return reverse('zdlra:zdlradatabase-detail', kwargs={'pk': self.pk})


class ZdlraDatabaseSpaceMetric(Metric):
    """Zdlra database space metric"""

    zdlradatabase = models.ForeignKey(ZdlraDatabase, on_delete=models.CASCADE)
    space_usage = models.PositiveIntegerField('Space usage')
    disk_reserved_space = models.PositiveIntegerField('Disk reserved space')
    size_estimate = models.PositiveIntegerField('Size estimate')
    recovery_window_space = models.PositiveIntegerField('Recovery window space')
    restore_window = models.DurationField('Restore window')
    unprotected_window = models.DurationField('Unprotected window')
    minimum_recovery_needed = models.DurationField('Minimum recovery needed')

    class Meta(Metric.Meta):
        db_table = 'zdlra_zdlra_database_space_metric'

zdlra/views/browser.py
"""Zdlra browser views"""

from csv_export.views import CSVExportView

from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DetailView

from zdlra.models import Zdlra, ZdlraDatabase, ZdlraProtectionPolicy, ZdlraDatabaseSpaceMetric


class ZdlraListView(LoginRequiredMixin, ListView):
    """Zdlra list view"""

    model = Zdlra


class ZdlraExportView(CSVExportView):
    """Zdlra export view"""

    model = Zdlra
    fields = "__all__"


class ZdlraDetailView(LoginRequiredMixin, DetailView):
    """Zdlra detail view"""

    model = Zdlra


class ZdlraProtectionPolicyListView(LoginRequiredMixin, ListView):
    """Zdlra protection policy list view"""

    model = ZdlraProtectionPolicy
    queryset = ZdlraProtectionPolicy.objects.all().select_related()


class ZdlraProtectionPolicyExportView(CSVExportView):
    """Zdlra protection policy export view"""

    model = ZdlraProtectionPolicy
    fields = "__all__"


class ZdlraProtectionPolicyDetailView(LoginRequiredMixin, DetailView):
    """Zdlra protection policy detail view"""

    model = ZdlraProtectionPolicy


class ZdlraDatabaseListView(LoginRequiredMixin, ListView):
    """Zdlra database list view"""

    model = ZdlraDatabase


class ZdlraDatabaseExportView(CSVExportView):
    """Database export view"""

    model = ZdlraDatabase
    fields = "__all__"


class ZdlraDatabaseDetailView(LoginRequiredMixin, DetailView):
    """Zdlra database detail view"""

    model = ZdlraDatabase

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)

        # Add in a QuerySet of last zdlra database metrics
        context['last_metric'] = ZdlraDatabaseSpaceMetric.objects.filter(
            zdlradatabase=context['zdlradatabase'],
            snapshot=context['zdlradatabase'].snapshot
        ).first()
        return context

zdlra/templates/zdlra/zdlra.html
{% extends "core/skeleton.html" %}

{% block breadcrumb %}
{{ block.super }}
<li class="breadcrumb-item"><a href="{% url 'zdlra:zdlra-list' %}">Zdlra</a></li>
{% endblock %}

zdlra/templates/zdlra/zdlra_detail.html
{% extends "zdlra/zdlra.html" %}
{% load mathfilters %}

{% block breadcrumb %}
{{ block.super }}
<li class="breadcrumb-item">{{ object.name }}</li>
{% endblock %}

{% block content %}
<table class="table">
    <tbody>
        <tr>
            <th>Name</th>
            <td>{{ object.name }}</td>
        </tr>
        <tr>
            <th>Snapshot date</th>
            <td><!-- Snapshot ID : {{ object.snapshot.id }} -->{{ object.snapshot.date }}</td>
        </tr>
    </tbody>
</table>

<div class="w-50">
    <canvas id="zdlraSpace"></canvas>
</div>

<ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
    <li class="nav-item" role="presentation">
        <button class="nav-link active" id="pills-databases-tab" data-bs-toggle="pill" data-bs-target="#pills-databases" type="button" role="tab" aria-controls="pills-databases" aria-selected="true">Databases</button>
    </li>
    <li class="nav-item" role="presentation">
        <button class="nav-link" id="pills-protection-policy-tab" data-bs-toggle="pill" data-bs-target="#pills-protection-policy" type="button" role="tab" aria-controls="pills-protection-policy" aria-selected="false">Protection policy</button>
    </li>
</ul>
<div class="tab-content" id="pills-tabContent">
    <div class="tab-pane fade show active" id="pills-databases" role="tabpanel" aria-labelledby="pills-databases-tab" tabindex="0">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Database</th>
                </tr>
            </thead>
            <tbody class="table-group-divider">
                {% for database in object.zdlradatabase_set.all.select_related %}
                <tr>
                    <td><a href="{{ database.get_absolute_url }}">{{ database }}</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="tab-pane fade" id="pills-protection-policy" role="tabpanel" aria-labelledby="pills-protection-policy-tab" tabindex="0">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Protection policy</th>
                </tr>
            </thead>
            <tbody class="table-group-divider">
                {% for protection_policy in object.zdlraprotectionpolicy_set.all %}
                <tr>
                    <td><a href="{{ protection_policy.get_absolute_url }}">{{ protection_policy }}</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

{% block js_file %}
{{ block.super }}
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-annotation@2.1.0/dist/chartjs-plugin-annotation.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chartjs-adapter-date-fns/dist/chartjs-adapter-date-fns.bundle.min.js"></script>
{% endblock %}

{% block js_script %}
{{ block.super }}
<script>
    document.addEventListener("DOMContentLoaded", function () {
        const data = {
            "datasets":[
                {
                    data:[
                        {% for metric in object.zdlraspacemetric_set.all.select_related %}
                        {
                        "x":'{{metric.date | date:"Y-m-d H:i:s"}}',
                        "y":{{metric.used|intdiv:1024}}
                        },{% endfor %}
                    ],
                    label:"Used Tb",
                    tension: 0.4,
                    cubicInterpolationMode: 'monotone',
                },
            ]
        };
        new Chart(
            document.getElementById("zdlraSpace"), 
            {
                type: "line",
                data: data,
                options: {
                    scales: {
                        x: {
                            type: "time",
                            time: {
                                unit: 'month'
                            }
                        },
                        y: {
                            max: 250
                        }
                    },
                    plugins: {
                        title: {
                            display: true,
                            text: 'ZDLRA Space usage'
                        },
                        annotation: {
                            annotations: {
                                line1: {
                                    type: 'line',
                                    yMin: 213,
                                    yMax: 213,
                                    borderColor: 'rgb(255, 99, 132)',
                                    borderWidth: 2,
                                }
                            }
                        }
                    }
                }
        });
    });
</script>
{% endblock %}

zdlra/templates/zdlra/zdlra_list.html
{% extends "zdlra/zdlra.html" %}
{% load mathfilters %}

{% block content %}
<a href="{% url 'zdlra:zdlra-export' %}"><i class="bi-filetype-csv" style="font-size: 2rem;"></i></a>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Name</th>
        </tr>
    </thead>
    <tbody class="table-group-divider">
        {% for object in object_list %}
        <tr>
            <td><a href="{{ object.get_absolute_url }}">{{ object }}</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<div class="w-50">
    <canvas id="zdlraSpace"></canvas>
</div>

{% endblock %}

{% block js_file %}
{{ block.super }}
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-annotation@2.1.0/dist/chartjs-plugin-annotation.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chartjs-adapter-date-fns/dist/chartjs-adapter-date-fns.bundle.min.js"></script>
{% endblock %}

{% block js_script %}
{{ block.super }}
<script>
    document.addEventListener("DOMContentLoaded", function () {
        const data = {
            "datasets":[{% for zdlra in object_list %}
                {
                    data:[
                        {% for metric in zdlra.zdlraspacemetric_set.all.select_related %}
                        {
                        "x":'{{metric.date | date:"Y-m-d H:i:s"}}',
                        "y":{{metric.used|intdiv:1024}}
                        },{% endfor %}
                    ],
                    label:"{{ zdlra }}",
                    tension: 0.4,
                    cubicInterpolationMode: 'monotone',
                },{% endfor %}
            ]
        };
        new Chart(
            document.getElementById("zdlraSpace"), 
            {
                type: "line",
                data: data,
                options: {
                    scales: {
                        x: {
                            type: "time",
                            time: {
                                unit: 'month'
                            }
                        },
                        y: {
                            max: 250,
                            title: {
                                text: "Used Tb",
                                display: true
                            }
                        }
                    },
                    plugins: {
                        title: {
                            display: true,
                            text: 'ZDLRA Space usage'
                        },
                        {% with first_metric=object_list.first.zdlraspacemetric_set.last %}
                        annotation: {
                            annotations: {
                                line1: {
                                    type: 'line',
                                    yMin: {{ first_metric.size|intdiv:1024 }},
                                    yMax: {{ first_metric.size|intdiv:1024 }},
                                    borderColor: 'rgb(255, 99, 132)',
                                    borderWidth: 2,
                                }
                            }
                        }
                        {% endwith %}
                    }
                }
        });
    });
</script>
{% endblock %}

zdlra/templates/zdlra/zdlradatabase.html
{% extends "zdlra/zdlra.html" %}

{% block breadcrumb %}
{{ block.super }}
<li class="breadcrumb-item"><a href="{% url 'zdlra:zdlradatabase-list' %}">ZLDRA Databases</a></li>
{% endblock %}

zdlra/templates/zdlra/zdlradatabase_detail.html
{% extends "zdlra/zdlra.html" %}

{% block breadcrumb %}
{{ block.super }}
<li class="breadcrumb-item">{{ object.database }}</li>
{% endblock %}

{% block content %}
<table class="table">
    <tbody>
        <tr>
            <th>Name</th>
            <td>{{ object.database }}</td>
        </tr>
        <tr>
            <th>State</th>
            <td>{{ object.state }}</td>
        </tr>
        <tr>
            <th>Creation time</th>
            <td>{{ object.creation_time }}</td>
        </tr>
        <tr>
            <th>Redo transport active</th>
            <td>{{ object.nzdl_active }}</td>
        </tr>
        <tr>
            <th>ZDLRA</th>
            <td>{{ object.zdlra }}</td>
        </tr>
        <tr>
            <th>Protection policy</th>
            <td>{{ object.protection_policy }}</td>
        </tr>
        <tr>
            <th>Snapshot date</th>
            <td>{{ object.snapshot.date }}</td>
        </tr>
        <tr>
            <th>Space usage</th>
            <td>{{ last_metric.space_usage }}</td>
        </tr>
        <tr>
            <th>Disk reserved space</th>
            <td>{{ last_metric.disk_reserved_space }}</td>
        </tr>
        <tr>
            <th>Size estimate</th>
            <td>{{ last_metric.size_estimate }}</td>
        </tr>
        <tr>
            <th>Recovery window space</th>
            <td>{{ last_metric.recovery_window_space }}</td>
        </tr>
        <tr>
            <th>Restore window</th>
            <td>{{ last_metric.restore_window }}</td>
        </tr>
        <tr>
            <th>Unprotected window</th>
            <td>{{ last_metric.unprotected_window }}</td>
        </tr>
        <tr>
            <th>Minimum recovery needed</th>
            <td>{{ last_metric.minimum_recovery_needed }}</td>
        </tr>
        <tr>
            <th>Snapshot date</th>
            <td><!-- Snapshot ID : {{ object.snapshot.id }} -->{{ object.snapshot.date }}</td>
        </tr>
    </tbody>
</table>
{% endblock %}

zdlra/templates/zdlra/zdlradatabase_list.html
{% extends "zdlra/zdlradatabase.html" %}

{% block content %}
<a href="{% url 'zdlra:zdlradatabase-export' %}"><i class="bi-filetype-csv" style="font-size: 2rem;"></i></a>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Name</th>
        </tr>
    </thead>
    <tbody class="table-group-divider">
        {% for object in object_list %}
        <tr>
            <td><a href="{{ object.get_absolute_url }}">{{ object }}</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

zdlra/templates/zdlra/zdlraprotectionpolicy.html
{% extends "zdlra/zdlra.html" %}

{% block breadcrumb %}
{{ block.super }}
<li class="breadcrumb-item"><a href="{% url 'zdlra:zdlraprotectionpolicy-list' %}">Protection Policy</a></li>
{% endblock %}

zdlra/templates/zdlra/zdlraprotectionpolicy_detail.html
{% extends "zdlra/zdlraprotectionpolicy.html" %}

{% block breadcrumb %}
{{ block.super }}
<li class="breadcrumb-item">{{ object.name }}</li>
{% endblock %}

{% block content %}
<table class="table">
    <tbody>
        <tr>
            <th>Name</th>
            <td>{{ object.name }}</td>
        </tr>
        <tr>
            <th>ZDLRA</th>
            <td>{{ object.zdlra }}</td>
        </tr>
    </tbody>
</table>

<ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
    <li class="nav-item" role="presentation">
        <button class="nav-link active" id="pills-databases-tab" data-bs-toggle="pill" data-bs-target="#pills-databases" type="button" role="tab" aria-controls="pills-databases" aria-selected="true">Databases</button>
    </li>
</ul>
<div class="tab-content" id="pills-tabContent">
    <div class="tab-pane fade show active" id="pills-databases" role="tabpanel" aria-labelledby="pills-databases-tab" tabindex="0">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Database</th>
                </tr>
            </thead>
            <tbody class="table-group-divider">
                {% for database in object.zdlradatabase_set.all %}
                <tr>
                    <td><a href="{{ database.get_absolute_url }}">{{ database }}</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

zdlra/templates/zdlra/zdlraprotectionpolicy_list.html
{% extends "zdlra/zdlraprotectionpolicy.html" %}

{% block content %}
<a href="{% url 'zdlra:zdlraprotectionpolicy-export' %}"><i class="bi-filetype-csv" style="font-size: 2rem;"></i></a>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Name</th>
        </tr>
    </thead>
    <tbody class="table-group-divider">
        {% for object in object_list %}
        <tr>
            <td><a href="{{ object.get_absolute_url }}">{{ object }}</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}