system/models.py
"""System app models"""
from django.db import models
from django.urls import reverse

from core.models import Environment, Metric, Snapshot, Vendor


# pylint: disable=R0903
class ClusterManager(models.Manager):
    """Cluster manager"""

    def search(self, query=None):
        """Search for cluster"""

        qs = self.get_queryset()
        if query is not None:
            or_lookup = models.Q(name__icontains=query)
            qs = qs.filter(or_lookup).order_by('name')
        return qs


class Cluster(models.Model):
    """Cluster model"""

    name = models.CharField('Name', max_length=255)

    objects = ClusterManager()

    class Meta:
        ordering = ['name']
        constraints = [
            models.UniqueConstraint(fields=['name'], name='cluster_set_unique')
        ]

    def __str__(self):
        return f"{self.name}"

    def get_absolute_url(self):
        """Return object absolute url"""

        return reverse('system:cluster-detail', kwargs={'pk': self.pk})


# pylint: disable=R0903
class ServerManager(models.Manager):
    """Server manager"""

    def search(self, query=None):
        """Search for server"""

        qs = self.get_queryset()
        if query is not None:
            or_lookup = models.Q(name__icontains=query)
            qs = qs.filter(or_lookup).order_by('name')
        return qs


class Server(models.Model):
    """Server model"""

    name = models.CharField('Name', max_length=255)
    nb_cores = models.PositiveIntegerField('Number of core on server', blank=True, null=True)
    memtotal_mb = models.PositiveIntegerField('Total memory of server', blank=True, null=True)
    site = models.CharField('Server site', max_length=16, blank=True, null=True)

    snapshot = models.ForeignKey(Snapshot, on_delete=models.CASCADE, blank=True, null=True)
    environment = models.ForeignKey(Environment, on_delete=models.CASCADE, blank=True, null=True)
    cluster = models.ForeignKey(Cluster, on_delete=models.CASCADE, blank=True, null=True)

    objects = ServerManager()

    class Meta:
        ordering = ['name']
        constraints = [
            models.UniqueConstraint(fields=['name'], name='server_set_unique')
        ]

    def __str__(self):
        return f"{self.name}"

    def get_absolute_url(self):
        """Return object absolute url"""

        return reverse('system:server-detail', kwargs={'pk': self.pk})


class Filesystem(models.Model):
    """Filesystem model"""

    mount_point = models.CharField('Mount point', max_length=255)
    type = models.CharField('Filesystem type', max_length=8)

    server = models.ForeignKey(Server, on_delete=models.CASCADE)
    snapshot = models.ForeignKey(Snapshot, on_delete=models.CASCADE)

    class Meta:
        ordering = ['mount_point']
        constraints = [
            models.UniqueConstraint(fields=['mount_point', 'server'], name='filesystem_set_unique')
        ]

    def __str__(self):
        return f"{self.mount_point} ({self.type})"

    def get_absolute_url(self):
        """Return object absolute url"""

        return reverse('system:filesystem-detail', kwargs={'pk': self.pk})


class FilesystemSizeMetric(Metric):
    """Filesystem size metric model"""

    filesystem = models.ForeignKey(Filesystem, on_delete=models.CASCADE)
    size = models.PositiveBigIntegerField('Size')
    used = models.PositiveBigIntegerField('Used')

    class Meta(Metric.Meta):
        db_table = 'system_filesystem_size_metric'


class Devices(models.Model):
    """Devices model"""

    name = models.CharField('Name', max_length=255)
    size_gb = models.PositiveBigIntegerField('Size Gb')

    server = models.ForeignKey(Server, on_delete=models.CASCADE)
    vendor = models.ForeignKey(Vendor, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name} ({self.size_gb})"


class NetworkInterface(models.Model):
    """NetworkInterface model"""

    PHYSICAL = 'PHYSICAL'
    BONDED = 'BONDED'

    NETIF_TYPE = [
        (PHYSICAL, 'Physical'),
        (BONDED, 'Bonded'),
    ]

    name = models.CharField('Name', max_length=16)
    type = models.CharField(max_length=8, choices=NETIF_TYPE)
    speed = models.PositiveIntegerField('Speed in Mb', null=True, blank=True)
    mtu = models.PositiveIntegerField('MTU', null=True, blank=True)
    active = models.BooleanField("Is it interface active")

    lacp_rate = models.CharField('LACP rate', max_length=16, null=True, blank=True)
    mode = models.CharField('LACP mode', max_length=16, null=True, blank=True)

    server = models.ForeignKey(Server, on_delete=models.CASCADE)
    slave_interfaces = models.ManyToManyField("self", symmetrical=False)

    class Meta:
        ordering = ['name']
        constraints = [
            models.UniqueConstraint(fields=['name', 'server'], name='networkinterface_set_unique')
        ]

    def __str__(self):
        return f"{self.name}"


class IpAddress(models.Model):
    """IpAddress model"""

    address = models.GenericIPAddressField('IP address')
    netmask = models.GenericIPAddressField('IP netmask')
    network = models.GenericIPAddressField('IP network')
    prefix = models.PositiveIntegerField('IP network prefix')
    is_primary = models.BooleanField("Is it the primary interface IP", default=True)

    interface = models.ForeignKey(NetworkInterface, on_delete=models.CASCADE)

    class Meta:
        ordering = ['address']
        constraints = [
            models.UniqueConstraint(fields=['address', 'interface'], name='ipaddress_set_unique')
        ]

    def __str__(self):
        ip_type = ""
        if not self.is_primary:
            ip_type = " (VIP)"
        return f"{self.address}{ip_type}"

system/forms.py
"""System forms"""

from django.forms import ModelForm

from system.models import Server

class ServerForm(ModelForm):
    """Server form"""

    class Meta:
        model = Server
        fields = ('__all__')
        exclude = ['snapshot']

system/views/browser.py
"""System browser views"""

from csv_export.views import CSVExportView

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic import CreateView, ListView, DetailView
from system.forms import ServerForm

from system.models import Cluster, Server, Filesystem


class ClusterListView(LoginRequiredMixin, ListView):
    """Cluster list view"""

    model = Cluster
    paginate_by = 10


class ClusterExportView(CSVExportView):
    """Cluster export view"""

    model = Cluster
    fields = "__all__"


class ClusterDetailView(LoginRequiredMixin, DetailView):
    """Cluster detail view"""

    model = Cluster


class ServerListView(LoginRequiredMixin, ListView):
    """Server list view"""

    model = Server
    paginate_by = 10


class ServerExportView(CSVExportView):
    """Server export view"""

    model = Server
    fields = "__all__"


class ServerDetailView(LoginRequiredMixin, DetailView):
    """Server detail view"""

    model = Server


class ServerCreate(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    """Server create view"""

    model = Server
    form_class = ServerForm
    success_message = "%(name)s successfully added"


class FilesystemDetailView(LoginRequiredMixin, DetailView):
    """Filesystem detail view"""

    model = Filesystem

system/templates/system/cluster.html
{% extends "core/skeleton.html" %}

{% block breadcrumb %}
{{ block.super }}
<li class="breadcrumb-item"><a href="{% url 'system:cluster-list' %}">Clusters</a></li>
{% endblock %}

system/templates/system/cluster_detail.html
{% extends "system/cluster.html" %}

{% block breadcrumb %}
{{ block.super }}
<li class="breadcrumb-item">{{ object.name }}</li>
{% endblock %}

{% block content %}
<table class="table">
    <tbody>
        <tr>
            <th>Name</th>
            <td>{{ object.name }}</td>
        </tr>
    </tbody>
</table>

<ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
    <li class="nav-item" role="presentation">
        <button class="nav-link active" id="pills-home-tab" data-bs-toggle="pill" data-bs-target="#pills-home" type="button" role="tab" aria-controls="pills-home" aria-selected="true">Servers</button>
    </li>
    <li class="nav-item" role="presentation">
        <button class="nav-link" id="pills-listeners-tab" data-bs-toggle="pill" data-bs-target="#pills-listeners" type="button" role="tab" aria-controls="pills-listeners" aria-selected="true">Listeners</button>
    </li>
</ul>
<div class="tab-content" id="pills-tabContent">
    <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab" tabindex="0">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Servers</th>
                </tr>
            </thead>
            <tbody class="table-group-divider">
                {% for server in object.server_set.all %}
                <tr>
                    <td><a href="{{ server.get_absolute_url }}">{{ server }}</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="tab-pane fade" id="pills-listeners" role="tabpanel" aria-labelledby="pills-listeners-tab" tabindex="0">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Nom</th>
                </tr>
            </thead>
            <tbody class="table-group-divider">
                {% for listener in object.scanlistener_set.all %}
                <tr>
                    <td><a href="{{ listener.get_absolute_url }}">{{ listener }}</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

system/templates/system/cluster_list.html
{% extends "system/cluster.html" %}

{% block content %}
{% include "core/paginator.html" %}
<a href="{% url 'system:cluster-export' %}"><i class="bi-filetype-csv" style="font-size: 2rem;"></i></a>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Name ({{ paginator.count }})</th>
        </tr>
    </thead>
    <tbody class="table-group-divider">
        {% for object in object_list %}
        <tr>
            <td><a href="{{ object.get_absolute_url }}">{{ object }}</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% include "core/paginator.html" %}

{% endblock %}

system/templates/system/filesystem.html
{% extends "core/skeleton.html" %}

{% block breadcrumb %}
{{ block.super }}
<li class="breadcrumb-item">Filesystems</li>
{% endblock %}

system/templates/system/filesystem_detail.html
{% extends "system/filesystem.html" %}
{% load mathfilters %}

{% block breadcrumb %}
{{ block.super }}
<li class="breadcrumb-item">{{ object.mount_point }}</li>
{% endblock %}

{% block content %}
<table class="table">
    <tbody>
        <tr>
            <th>Server</th>
            <td><a href="{{ object.server.get_absolute_url }}">{{ object.server }}</a></td>
        </tr>
        <tr>
            <th>Mount point</th>
            <td>{{ object.mount_point }}</td>
        </tr>
        <tr>
            <th>Type</th>
            <td>{{ object.type }}</td>
        </tr>
        <tr>
            <th>Snapshot date</th>
            <td><!-- Snapshot ID : {{ object.snapshot.id }} -->{{ object.snapshot.date }}</td>
        </tr>
    </tbody>
</table>

<ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
    <li class="nav-item" role="presentation">
        <button class="nav-link active" id="pills-fsSize-tab" data-bs-toggle="pill" data-bs-target="#pills-fsSize" type="button" role="tab" aria-controls="pills-fsSize" aria-selected="true">Filesystem Size</button>
    </li>
</ul>
<div class="tab-content" id="pills-tabContent">
    <div class="tab-pane fade show active" id="pills-fsSize" role="tabpanel" aria-labelledby="pills-fsSize-tab" tabindex="0">
        <div class="w-50">
            <canvas id="fsSize"></canvas>
        </div>
    </div>
</div>
{% endblock %}

{% block js_file %}
{{ block.super }}
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-annotation@2.1.0/dist/chartjs-plugin-annotation.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chartjs-adapter-date-fns/dist/chartjs-adapter-date-fns.bundle.min.js"></script>
{% endblock %}

{% block js_script %}
{{ block.super }}
<script>
    var dataFilesystemSize = []
    var dataFilesystemUsed = []

    {% for metric in object.filesystemsizemetric_set.all %}
    dataFilesystemSize.push({"x":'{{metric.date | date:"Y-m-d H:i:s"}}',"y":{{metric.size|intdiv:1073741824}}});
    dataFilesystemUsed.push({"x":'{{metric.date | date:"Y-m-d H:i:s"}}',"y":{{metric.used|intdiv:1073741824}}});
    {% endfor %}


    document.addEventListener("DOMContentLoaded", function () {
        const dataFsSize = {
            "datasets":[
                {
                    data: dataFilesystemSize,
                    label: "Size",
                    tension: 0.4,
                    cubicInterpolationMode: 'monotone',
                },{
                    data: dataFilesystemUsed,
                    label: "Used",
                    tension: 0.4,
                    cubicInterpolationMode: 'monotone',
                },
            ]
        };
        new Chart(
            document.getElementById("fsSize"), 
            {
                type: "line",
                data: dataFsSize,
                options: {
                    scales: {
                        x: {
                            type: "time",
                            time: {
                                unit: 'month'
                            }
                        },
                        y: {
                            title: {
                                text: "Used Gb",
                                display: true
                            }
                        }
                    },
                    plugins: {
                        title: {
                            display: true,
                            text: 'Filesystem Size'
                        },
                    }
                }
        });
    });
</script>
{% endblock %}

system/templates/system/server.html
{% extends "core/skeleton.html" %}

{% block breadcrumb %}
{{ block.super }}
<li class="breadcrumb-item"><a href="{% url 'system:server-list' %}">Servers</a></li>
{% endblock %}

system/templates/system/server_detail.html
{% extends "system/server.html" %}

{% block breadcrumb %}
{{ block.super }}
<li class="breadcrumb-item">{{ object.name }}</li>
{% endblock %}

{% block content %}
<table class="table">
    <tbody>
        <tr>
            <th>Environment</th>
            <td>{{ object.environment }}</td>
        </tr>
        <tr>
            <th>Name</th>
            <td>{{ object.name }}</td>
        </tr>
        <tr>
            <th>Site</th>
            <td>{{ object.site }}</td>
        </tr>
        <tr>
            <th>Cluster</th>
            <td><a href="{{ object.cluster.get_absolute_url }}">{{ object.cluster }}</a></td>
         </tr>
        <tr>
            <th>Nb CPU core</th>
            <td>{{ object.nb_cores }}</td>
        </tr>
        <tr>
            <th>Memory Mb</th>
            <td>{{ object.memtotal_mb }}</td>
        </tr>
        <tr>
            <th>Snapshot date</th>
            <td><!-- Snapshot ID : {{ object.snapshot.id }} -->{{ object.snapshot.date }}</td>
        </tr>
    </tbody>
</table>

<ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
    <li class="nav-item" role="presentation">
        <button class="nav-link active" id="pills-home-tab" data-bs-toggle="pill" data-bs-target="#pills-home" type="button" role="tab" aria-controls="pills-home" aria-selected="true">Instances</button>
    </li>
    <li class="nav-item" role="presentation">
        <button class="nav-link" id="pills-filesystem-tab" data-bs-toggle="pill" data-bs-target="#pills-filesystem" type="button" role="tab" aria-controls="pills-filesystem" aria-selected="true">Filesystems</button>
    </li>
    <li class="nav-item" role="presentation">
        <button class="nav-link" id="pills-netif-tab" data-bs-toggle="pill" data-bs-target="#pills-netif" type="button" role="tab" aria-controls="pills-netif" aria-selected="true">Network interfaces</button>
    </li>
    <li class="nav-item" role="presentation">
        <button class="nav-link" id="pills-listeners-tab" data-bs-toggle="pill" data-bs-target="#pills-listeners" type="button" role="tab" aria-controls="pills-listeners" aria-selected="true">Listeners</button>
    </li>
</ul>
<div class="tab-content" id="pills-tabContent">
    <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab" tabindex="0">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Name</th>
                </tr>
            </thead>
            <tbody class="table-group-divider">
                {% for instance in object.instance_set.all %}
                <tr>
                    <td><a href="{{ instance.get_absolute_url }}">{{ instance }}</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="tab-pane fade" id="pills-filesystem" role="tabpanel" aria-labelledby="pills-filesystem-tab" tabindex="0">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Filesystem</th>
                </tr>
            </thead>
            <tbody class="table-group-divider">
                {% for filesystem in object.filesystem_set.all %}
                <tr>
                    <td><a href="{{ filesystem.get_absolute_url }}">{{ filesystem }}</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="tab-pane fade" id="pills-netif" role="tabpanel" aria-labelledby="pills-netif-tab" tabindex="0">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Interface</th>
                    <th>Status</th>
                    <th>IPS</th>
                </tr>
            </thead>
            <tbody class="table-group-divider">
                {% for interface in object.networkinterface_set.all %}
                <tr>
                    <td>{{ interface }}</td>
                    <td>{{ interface.active }}</td>
                    <td>
                        {% for ip in interface.ipaddress_set.all %}
                        {{ ip }}<br />
                        {% endfor %}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="tab-pane fade" id="pills-listeners" role="tabpanel" aria-labelledby="pills-listeners-tab" tabindex="0">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Nom</th>
                </tr>
            </thead>
            <tbody class="table-group-divider">
                {% for listener in object.locallistener_set.all %}
                <tr>
                    <td><a href="{{ listener.get_absolute_url }}">{{ listener }}</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

system/templates/system/server_form.html
{% extends "core/skeleton.html" %}

{% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table class="table table-striped">
    {{ form }}
    </table>
    <input type="submit" value="Enregistrer"> <a href="{% if server %}{{ server.get_absolute_url }}{% else %}{% url 'system:server-list' %}{% endif %}"><input type="button" value="Abandoner"></a>
</form>
{% endblock %}

system/templates/system/server_list.html
{% extends "system/server.html" %}

{% block content %}
{% include "core/paginator.html" %}
<a href="{% url 'system:server-add' %}"><i class="bi-plus-square" style="font-size: 2rem;"></i></a>
<a href="{% url 'system:server-export' %}"><i class="bi-filetype-csv" style="font-size: 2rem;"></i></a>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Name ({{ paginator.count }})</th>
            <th>Environment</th>
        </tr>
    </thead>
    <tbody class="table-group-divider">
        {% for server in object_list %}
        <tr>
            <td><a href="{{ server.get_absolute_url }}">{{ server }}</a></td>
            <td>{{ server.environment }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% include "core/paginator.html" %}

{% endblock %}