database/models/__init__.py
"""Database type definition"""

class DatabaseType:
    """List of database type"""

    ORACLE = 'ORA'
    SQLSERVER = 'SQL'
    POSTGRES = 'PGS'

    TYPE = [
        (ORACLE, 'Oracle'),
        (SQLSERVER, 'SQLServer'),
        (POSTGRES, 'PostgreSQL'),
    ]

database/models/database/__init__.py
"""Database base models"""

from django.db import models
from django.urls import reverse

from core.models import Metric, Snapshot
from database.models import DatabaseType
from database.models.instance import Instance


class DatabaseReplicationSystem(models.Model):
    """Database repliacation system model"""

    name = models.CharField('Name', max_length=9)
    system_id = models.CharField('Unique replication system identifier', max_length=64)

    class Meta:
        db_table = 'database_database_replication_system'
        constraints = [
            models.UniqueConstraint(
                fields=['name', 'system_id'], name='databasereplicationsystem_set_unique')
        ]


# pylint: disable=R0903
class DatabaseManager(models.Manager):
    """Database manager"""

    def search(self, query=None):
        """Search for database"""

        qs = self.get_queryset()
        if query is not None:
            or_lookup = (
                models.Q(name__icontains=query)
            )
            # distinct() is often necessary with Q lookups
            qs = qs.filter(or_lookup).order_by('name')
        return qs


class Database(models.Model):
    """Base database model"""

    name = models.CharField('Name of this database', max_length=128)
    type = models.CharField(max_length=3, choices=DatabaseType.TYPE)
    cluster_id = models.CharField('Unique cluster identifier', max_length=64)

    instances = models.ManyToManyField(Instance)
    snapshot = models.ForeignKey(Snapshot, on_delete=models.CASCADE)

    objects = DatabaseManager()

    class Meta:
        db_table = 'database_database'
        ordering = ['name']
        constraints = [
            models.UniqueConstraint(
                fields=['name', 'cluster_id'], name='database_set_unique')
        ]

    def __str__(self):
        """Return string representation"""
        return f"{self.name} ({self.get_type_display()})"

    def get_absolute_url(self):
        """Return object absolute url"""

        if self.type == DatabaseType.ORACLE:
            return self.oracledatabase.get_absolute_url()  # pylint: disable=no-member

        return reverse('database:database-detail', kwargs={'pk': self.pk})

    def get_sites(self):
        """Return the site of servers hosting this database"""

        sites = []
        for instance in self.instances.all().select_related("server"):
            if instance.server.site not in sites:
                sites.append(instance.server.site)

        return sites

    def get_host(self):
        """Return a tuple of host type and host name"""

        server = self.instances.first().server

        # Don't want the FQDN, so split on "." and return first element
        if server.cluster:
            return ("cluster", server.cluster.name.split('.')[0])

        return ("cluster", server.name.split('.')[0])


class DatabaseSizeMetric(Metric):
    """Database size metric"""

    database = models.ForeignKey(Database, on_delete=models.CASCADE)
    size = models.PositiveBigIntegerField('Total database size')
    datafile_size = models.PositiveBigIntegerField('Datafiles size')
    redo_size = models.PositiveBigIntegerField('Redo size')
    tempfile_size = models.PositiveBigIntegerField('Tempfiles size')


    class Meta(Metric.Meta):
        db_table = 'database_database_size_metric'

database/models/diskgroup/__init__.py
from django.db import models

from core.models import Metric
from database.models.instance import Instance

class DiskgroupParameterMetric(Metric):
    """Diskgroup parameter metric model"""

    instance = models.ForeignKey(Instance, on_delete=models.CASCADE)
    name = models.CharField('Name', max_length=80)
    value = models.TextField('Value')

    class Meta(Metric.Meta):
        db_table = 'database_diskgroup_parameter_metric'
        ordering = ['name']

database/models/engine/__init__.py
from django.db import models
from django.urls import reverse

from system.models import Server

class Engine(models.Model):
    """Instance binary model"""

    path = models.CharField('Instance\'s binary', max_length=255)
    server = models.ForeignKey(Server, on_delete=models.CASCADE)
    version = models.CharField('Version', max_length=255)

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['path', 'server'], name='engine_set_unique')
        ]


    def __str__(self):
        return f"{self.path}"


    def get_absolute_url(self):
        """Return object absolute url"""

        return reverse('database:instancebinary-detail', kwargs={'pk': self.pk})

database/models/instance/__init__.py
"""Instance base models"""

from django.db import models
from django.urls import reverse

from core.models import Environment, Metric, Snapshot, Vendor
from database.models import DatabaseType
from database.models.engine import Engine
from system.models import Server


# pylint: disable=R0903
class InstanceManager(models.Manager):
    """Instance manager"""

    def search(self, query=None):
        """Search for instance"""

        qs = self.get_queryset()
        if query is not None:
            or_lookup = models.Q(name__icontains=query)
            # distinct() is often necessary with Q lookups
            qs = qs.filter(or_lookup).distinct()
        return qs


class Instance(models.Model):
    """Base instance model"""

    name = models.CharField('Name', max_length=255)
    type = models.CharField(max_length=3, choices=DatabaseType.TYPE)

    server = models.ForeignKey(Server, on_delete=models.CASCADE)
    vendor = models.ForeignKey(Vendor, on_delete=models.CASCADE)
    engine = models.ForeignKey(Engine, on_delete=models.CASCADE)
    snapshot = models.ForeignKey(Snapshot, on_delete=models.CASCADE)
    environment = models.ForeignKey(Environment, on_delete=models.CASCADE, blank=True, null=True)

    objects = InstanceManager()

    class Meta:
        db_table = 'database_instance'
        ordering = ['name']
        constraints = [
            models.UniqueConstraint(
                fields=['name', 'server'], name='instance_set_unique')
        ]

    def __str__(self):
        """Return string representation"""
        return f"{self.name} ({self.get_type_display()})"

    def get_absolute_url(self):
        """Return object absolute url"""

        if self.type == DatabaseType.ORACLE:
            return self.oracleinstance.get_absolute_url()  # pylint: disable=no-member

        return reverse('database:instance-detail', kwargs={'pk': self.pk})


class InstanceParameterMetric(Metric):
    """Instance parameter metric model"""

    instance = models.ForeignKey(Instance, on_delete=models.CASCADE)
    name = models.CharField('Name', max_length=80)
    value = models.TextField('Value')

    class Meta(Metric.Meta):
        db_table = 'database_instance_parameter_metric'
        ordering = ['name']

database/models/tablespace/__init__.py
"""Tablespace base models"""

from django.db import models
from django.urls import reverse

from core.models import Metric, Snapshot
from database.models import DatabaseType
from database.models.database import Database


# pylint: disable=R0903
class TablespaceManager(models.Manager):
    """Tablepsace manager"""

    def search(self, query=None):
        """Search for tablespace"""

        qs = self.get_queryset()
        if query is not None:
            or_lookup = (
                models.Q(name__icontains=query)
            )
            # distinct() is often necessary with Q lookups
            qs = qs.filter(or_lookup).order_by('name')
        return qs


class Tablespace(models.Model):
    """Tablespace model"""

    name = models.CharField('Name', max_length=30)
    type = models.CharField(max_length=3, choices=DatabaseType.TYPE)

    database = models.ForeignKey(Database, on_delete=models.CASCADE)
    snapshot = models.ForeignKey(Snapshot, on_delete=models.CASCADE)

    objects = TablespaceManager()

    class Meta:
        db_table = 'database_tablespace'
        ordering = ['name']
        constraints = [
            models.UniqueConstraint(
                fields=['name', 'database'], name='tablespace_set_unique')
        ]

    def __str__(self):
        return f"{self.name}"

    def get_absolute_url(self):
        """Return object absolute url"""

        if self.type == DatabaseType.ORACLE:
            return self.oracletablespace.get_absolute_url()  # pylint: disable=no-member


class TablespaceSpaceMetric(Metric):
    """Tablespace space metric"""

    tablespace = models.ForeignKey(Tablespace, on_delete=models.CASCADE)
    size = models.PositiveBigIntegerField('Size')
    used = models.PositiveBigIntegerField('Used')
    max_size = models.PositiveBigIntegerField('Max Size')

    class Meta(Metric.Meta):
        db_table = 'database_tablespace_space_metric'

database/models/tns/__init__.py
"""Tns base models"""

from django.db import models
from django.urls import reverse
from database.models.database import Database
from database.models.engine import Engine

from system.models import Cluster, Server

# class Listener(models.Model):
#     """Listener model"""

#     name = models.CharField('Name', max_length=30)
#     type = models.CharField(max_length=3, choices=DatabaseType.TYPE)
#     engine = models.ForeignKey(Engine, on_delete=models.CASCADE)

#     class Meta:
#         db_table = 'database_listener'
#         ordering = ['name']

#     def __str__(self):
#         """Return string representation"""
#         return f"{self.name}"

#     def get_absolute_url(self):
#         """Return object absolute url"""

#         if self.type == DatabaseType.ORACLE:
#             return self.oraclelistener.get_absolute_url()  # pylint: disable=no-member

class Listener(models.Model):
    """Listener model"""

    LOCAL = 'LOCAL'
    SCAN = 'SCAN'

    ORACLE_LISTENER_TYPE = [
        (LOCAL, 'Local Listener'),
        (SCAN, 'Scan Listener'),
    ]

    name = models.CharField('Name', max_length=30)
    type = models.CharField(max_length=5, choices=ORACLE_LISTENER_TYPE)
    engine = models.ForeignKey(Engine, on_delete=models.CASCADE)

    class Meta:
        db_table = 'database_listener'

    def __str__(self):
        """Return string representation"""
        return f"{self.name}"

    def get_absolute_url(self):
        """Return object absolute url"""

        if self.type == self.LOCAL:
            return self.locallistener.get_absolute_url()  # pylint: disable=no-member
        else:
            return self.scanlistener.get_absolute_url()  # pylint: disable=no-member


class LocalListener(Listener):
    """LocalListener model"""

    server = models.ForeignKey(Server, on_delete=models.CASCADE)

    class Meta:
        db_table = 'database_listener_local'

    def save(self, *args, **kwargs):
        self.type = Listener.LOCAL
        super().save(*args, **kwargs)

    def __str__(self):
        """Return string representation"""
        return f"{self.name} (Local Listener)"

    def get_absolute_url(self):
        """Return object absolute url"""
        return reverse('database:listener-local-detail', kwargs={'pk': self.pk})


class ScanListener(Listener):
    """ScanListener model"""

    cluster = models.ForeignKey(Cluster, on_delete=models.CASCADE)

    class Meta:
        db_table = 'database_listener_scan'

    def save(self, *args, **kwargs):
        self.type = Listener.SCAN
        super().save(*args, **kwargs)

    def __str__(self):
        """Return string representation"""
        return f"{self.name} (SCAN Listener)"

    def get_absolute_url(self):
        """Return object absolute url"""
        return reverse('database:listener-scan-detail', kwargs={'pk': self.pk})


class Endpoint(models.Model):
    """Endpoint model"""

    hostname = models.CharField('Hostname', max_length=255)
    port = models.PositiveSmallIntegerField('Port')

    listener = models.ForeignKey(Listener, on_delete=models.CASCADE)

    class Meta:
        db_table = 'database_endpoint'


# pylint: disable=R0903
class ServiceManager(models.Manager):
    """Service manager"""

    def search(self, query=None):
        """Search for service"""

        qs = self.get_queryset()
        if query is not None:
            or_lookup = (
                models.Q(name__icontains=query)
            )
            # distinct() is often necessary with Q lookups
            qs = qs.filter(or_lookup).order_by('name')
        return qs


class Service(models.Model):
    """Service Model"""

    name = models.CharField('Name', max_length=512)

    listeners = models.ManyToManyField(Listener)
    database = models.ForeignKey(Database, on_delete=models.CASCADE)

    objects = ServiceManager()

    class Meta:
        db_table = 'database_service'

    def __str__(self):
        """Return string representation"""
        return f"{self.name}"

    def get_absolute_url(self):
        """Return object absolute url"""
        return reverse('database:service-detail', kwargs={'pk': self.pk})

database/models/user/__init__.py
from django.db import models
from django.urls import reverse

from core.models import Metric, Snapshot
from database.models import DatabaseType
from database.models.database import Database


# pylint: disable=R0903
class UserManager(models.Manager):
    """User manager"""

    def search(self, query=None):
        """Search for user"""

        qs = self.get_queryset()
        if query is not None:
            or_lookup = (
                models.Q(name__icontains=query)
            )
            # distinct() is often necessary with Q lookups
            qs = qs.filter(or_lookup).distinct()
        return qs


class User(models.Model):
    """User model"""

    name = models.CharField('Username', max_length=128)
    type = models.CharField(max_length=3, choices=DatabaseType.TYPE)

    database = models.ForeignKey(Database, on_delete=models.CASCADE)
    snapshot = models.ForeignKey(Snapshot, on_delete=models.CASCADE)

    objects = UserManager()

    class Meta:
        db_table = 'database_user'
        ordering = ['name']
        constraints = [
            models.UniqueConstraint(
                fields=['database', 'name'], name='user_set_unique')
        ]

    def __str__(self):
        return f"{self.name}"

    def get_absolute_url(self):
        """Return object absolute url"""

        if self.type == DatabaseType.ORACLE:
            return self.oracleuser.get_absolute_url()


class UserSpaceMetric(Metric):
    """Tablespace space metric"""

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    size = models.PositiveBigIntegerField('Size')

    class Meta(Metric.Meta):
        db_table = 'database_user_space_metric'

database/templates/database/oracle/database_detail_cdb.html
{% extends "database/oracle/database_detail_container.html" %}
{% block container_type %}Multitenant CDB database{% endblock %}

database/templates/database/oracle/database_detail_container.html
{% extends "database/database.html" %}
{% load mathfilters %}

{% block breadcrumb %}
{{ block.super }}
<li class="breadcrumb-item">{{ object.name }}</li>
{% endblock %}

{% block content %}
<h1>{% block container_type %}{% endblock %}</h1>
<table class="table">
    <tbody>
        <tr>
            <th>Unique Name</th>
            <td>{{ object.name }}</td>
        </tr>
        <tr>
            <th>Global Name</th>
            <td>{{ object.global_name }}</td>
        </tr>
        <tr>
            <th>Type</th>
            <td>{{ object.get_type_display }}</td>
        </tr>
        <tr>
            <th>DBID</th>
            <td>{{ object.dbid }}</td>
        </tr>
        <tr>
            <th>Cluster Database</th>
            <td>{{ object.is_cluster_database }}</td>
        </tr>
        <tr>
            <th>Size</th>
            <td>{{ object.size | filesizeformat }}</td>
        </tr>
        <tr>
            <th>Creation date</th>
            <td>{{ object.created }}</td>
        </tr>
        <tr>
            <th>Resetlogs time</th>
            <td>{{ object.resetlogs_time }}</td>
        </tr>
        <tr>
            <th>Log mode</th>
            <td>{{ object.log_mode }}</td>
        </tr>
        <tr>
            <th>Role</th>
            <td>{{ object.database_role }}</td>
        </tr>
        <tr>
            <th>Force logging</th>
            <td>{{ object.force_logging }}</td>
        </tr>
        <tr>
            <th>Flashback on</th>
            <td>{{ object.flashback_on }}</td>
        </tr>
        <tr>
            <th>Snapshot date</th>
            <td><!-- Snapshot ID : {{ object.snapshot.id }} -->{{ object.snapshot.date }}</td>
        </tr>
    </tbody>
</table>

<ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
    <li class="nav-item" role="presentation">
        <button class="nav-link active" id="pills-instances-tab" data-bs-toggle="pill" data-bs-target="#pills-instances" type="button" role="tab" aria-controls="pills-instances" aria-selected="true">Instances</button>
    </li>
    <li class="nav-item" role="presentation">
        <button class="nav-link" id="pills-tablespaces-tab" data-bs-toggle="pill" data-bs-target="#pills-tablespaces" type="button" role="tab" aria-controls="pills-tablespaces" aria-selected="false">Tablespaces</button>
    </li>
    <li class="nav-item" role="presentation">
        <button class="nav-link" id="pills-users-tab" data-bs-toggle="pill" data-bs-target="#pills-users" type="button" role="tab" aria-controls="pills-users" aria-selected="false">Users</button>
    </li>
    <li class="nav-item" role="presentation">
        <button class="nav-link" id="pills-replication-tab" data-bs-toggle="pill" data-bs-target="#pills-replication" type="button" role="tab" aria-controls="pills-replication" aria-selected="false">Dataguard</button>
    </li>
    <li class="nav-item" role="presentation">
        <button class="nav-link" id="pills-dbsize-tab" data-bs-toggle="pill" data-bs-target="#pills-dbsize" type="button" role="tab" aria-controls="pills-dbsize" aria-selected="false">DB Size</button>
    </li>
    <li class="nav-item" role="presentation">
        <button class="nav-link" id="pills-fra-tab" data-bs-toggle="pill" data-bs-target="#pills-fra" type="button" role="tab" aria-controls="pills-fra" aria-selected="false">FRA</button>
    </li>
    <li class="nav-item" role="presentation">
        <button class="nav-link" id="pills-services-tab" data-bs-toggle="pill" data-bs-target="#pills-services" type="button" role="tab" aria-controls="pills-services" aria-selected="false">Services</button>
    </li>
</ul>
<div class="tab-content" id="pills-tabContent">
    <div class="tab-pane fade show active" id="pills-instances" role="tabpanel" aria-labelledby="pills-instances-tab" tabindex="0">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Instance</th>
                    <th>Server</th>
                </tr>
            </thead>
            <tbody class="table-group-divider">
                {% for instance in object.instances.all %}
                <tr>
                    <td><a href="{{ instance.get_absolute_url }}">{{ instance }}</a></td>
                    <td><a href="{{ instance.server.get_absolute_url }}">{{ instance.server }}</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="tab-pane fade" id="pills-tablespaces" role="tabpanel" aria-labelledby="pills-tablespaces-tab" tabindex="0">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Tablespace</th>
                    <th>Usage</th>
                    <th>Size</th>
                    <th>Used</th>
                </tr>
            </thead>
            <tbody class="table-group-divider">
                {% for tablespace in tablespaces %}
                {% widthratio tablespace.size_metric.used tablespace.size_metric.size 100 as used_percent %}
                <tr>
                    <td><a href="{{ tablespace.get_absolute_url }}">{{ tablespace.name }}</a></td>
                    <td>
                        <div class="progress">
                            <div class="progress-bar" role="progressbar" aria-label="Tablespace usage" style="width: {{ used_percent }}%;" aria-valuenow="{{ used_percent }}" aria-valuemin="0" aria-valuemax="100">{{ used_percent }}%</div>
                        </div>
                    </td>
                    <td>{{ tablespace.size_metric.size | filesizeformat }}</td>
                    <td>{{ tablespace.size_metric.used | filesizeformat }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="tab-pane fade" id="pills-users" role="tabpanel" aria-labelledby="pills-users-tab" tabindex="0">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>User</th>
                    <th>Size</th>
                </tr>
            </thead>
            <tbody class="table-group-divider">
                {% for user in oracle_users %}
                <tr>
                    <td><a href="{{ user.get_absolute_url }}">{{ user }}</a></td>
                    <td>{{ user.size_metric.size | filesizeformat }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="tab-pane fade" id="pills-replication" role="tabpanel" aria-labelledby="pills-replication-tab" tabindex="0">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Database</th>
                    <th>Role</th>
                </tr>
            </thead>
            <tbody class="table-group-divider">
                {% for database in object.replication_system.containeroracledatabase_set.all %}
                <tr>
                    <td><a href="{{ database.get_absolute_url }}">{{ database }}</a></td>
                    <td>{{ database.database_role }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="tab-pane fade" id="pills-dbsize" role="tabpanel" aria-labelledby="pills-dbsize-tab" tabindex="0">
        <div class="w-50">
            <canvas id="dbSize"></canvas>
        </div>
    </div>
    <div class="tab-pane fade" id="pills-fra" role="tabpanel" aria-labelledby="pills-fra-tab" tabindex="0">
        <div class="w-50">
            <canvas id="fraSpace"></canvas>
        </div>
    </div>
    <div class="tab-pane fade" id="pills-services" role="tabpanel" aria-labelledby="pills-services-tab" tabindex="0">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Services</th>
                </tr>
            </thead>
            <tbody class="table-group-divider">
                {% for service in object.service_set.all %}
                <tr>
                    <td><a href="{{ service.get_absolute_url }}">{{ service }}</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

{% block js_file %}
{{ block.super }}
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-annotation@2.1.0/dist/chartjs-plugin-annotation.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chartjs-adapter-date-fns/dist/chartjs-adapter-date-fns.bundle.min.js"></script>
{% endblock %}

{% block js_script %}
{{ block.super }}
<script>
    data_database_size = [];
    data_datafile_size = [];
    data_redo_size = [];
    data_tempfile_size = [];

    {% for metric in object.databasesizemetric_set.all %}
        data_database_size.push({"x":'{{metric.date | date:"Y-m-d H:i:s"}}',"y":{{metric.size|intdiv:1073741824}}});
        data_datafile_size.push({"x":'{{metric.date | date:"Y-m-d H:i:s"}}',"y":{{metric.datafile_size|intdiv:1073741824}}});
        data_redo_size.push({"x":'{{metric.date | date:"Y-m-d H:i:s"}}',"y":{{metric.redo_size|intdiv:1073741824}}});
        data_tempfile_size.push({"x":'{{metric.date | date:"Y-m-d H:i:s"}}',"y":{{metric.tempfile_size|intdiv:1073741824}}});
    {% endfor %}

    document.addEventListener("DOMContentLoaded", function () {
        const dataFra = {
            "datasets":[
                {
                    data:[
                        {% for metric in object.containeroracleframetric_set.all %}
                        {"x":'{{metric.date | date:"Y-m-d H:i:s"}}',"y":{{metric.used|intdiv:1073741824}}},{% endfor %}
                    ],
                    label:"{{ database }}",
                    tension: 0.4,
                    cubicInterpolationMode: 'monotone',
                },
            ]
        };
        const dataDbSize = {
            "datasets":[
                {
                    data: data_database_size,
                    label: "Database size",
                    tension: 0.4,
                    cubicInterpolationMode: 'monotone',
                },
                {
                    data: data_datafile_size,
                    label: "Datafile size",
                    tension: 0.4,
                    cubicInterpolationMode: 'monotone',
                },
                {
                    data: data_redo_size,
                    label: "Redo size",
                    tension: 0.4,
                    cubicInterpolationMode: 'monotone',
                },
                {
                    data: data_tempfile_size,
                    label: "Tempfile size",
                    tension: 0.4,
                    cubicInterpolationMode: 'monotone',
                },
            ]
        };
        new Chart(
            document.getElementById("fraSpace"), 
            {
                type: "line",
                data: dataFra,
                options: {
                    scales: {
                        x: {
                            type: "time",
                            time: {
                                unit: 'month'
                            }
                        },
                        y: {
                            title: {
                                text: "Used Gb",
                                display: true
                            }
                        }
                    },
                    plugins: {
                        title: {
                            display: true,
                            text: 'Database FRA usage'
                        },
                    }
                }
        });
        new Chart(
            document.getElementById("dbSize"), 
            {
                type: "line",
                data: dataDbSize,
                options: {
                    scales: {
                        x: {
                            type: "time",
                            time: {
                                unit: 'month'
                            }
                        },
                        y: {
                            title: {
                                text: "Used Gb",
                                display: true
                            }
                        }
                    },
                    plugins: {
                        title: {
                            display: true,
                            text: 'Database Size'
                        },
                    }
                }
        });
    });
</script>
{% endblock %}

database/templates/database/oracle/database_detail_leg.html
{% extends "database/oracle/database_detail_container.html" %}
{% block container_type %}Legacy database{% endblock %}

database/templates/database/oracle/instance-oracle-database-detail.html
{% extends "database/instance.html" %}

{% block breadcrumb %}
{{ block.super }}
<li class="breadcrumb-item">{{ object.name }}</li>
{% endblock %}

{% block content %}
<table class="table">
    <tbody>
        <tr>
            <th>Environment</th>
            <td>{{ object.environment }}</td>
        </tr>
        <tr>
            <th>Name</th>
            <td>{{ object.name }}</td>
        </tr>
        <tr>
            <th>Version</th>
            <td>{{ object.engine.version }}</td>
        </tr>
        <tr>
            <th>Oracle Home</th>
            <td>{{ object.engine }}</td>
        </tr>
        <tr>
            <th>Server</th>
            <td><a href="{{ object.server.get_absolute_url }}">{{ object.server }}</a></td>
        </tr>
        <tr>
            <th>Snapshot date</th>
            <td><!-- Snapshot ID : {{ object.snapshot.id }} -->{{ object.snapshot.date }}</td>
        </tr>
    </tbody>
</table>

<ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
    <li class="nav-item" role="presentation">
        <button class="nav-link active" id="pills-home-tab" data-bs-toggle="pill" data-bs-target="#pills-home" type="button" role="tab" aria-controls="pills-home" aria-selected="true">Databases</button>
    </li>
    <li class="nav-item" role="presentation">
        <button class="nav-link" id="pills-profile-tab" data-bs-toggle="pill" data-bs-target="#pills-profile" type="button" role="tab" aria-controls="pills-profile" aria-selected="false">Parameters</button>
    </li>
</ul>
<div class="tab-content" id="pills-tabContent">
    <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab" tabindex="0">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Name</th>
                </tr>
            </thead>
            <tbody class="table-group-divider">
                {% for database in object.database_set.all %}
                <tr>
                    <td><a href="{{ database.get_absolute_url }}">{{ database }}</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab" tabindex="0">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Value</th>
                </tr>
            </thead>
            <tbody class="table-group-divider">
                {% for metric in instance_metrics %}
                <tr> <!-- # {{ parameter.id }} -->
                    <td>{{ metric.name }}</td>
                    <td>{{ metric.value }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}