database/models/__init__.py
"""Database type definition"""

class DatabaseType:
    """List of database type"""

    ORACLE = 'ORA'
    SQLSERVER = 'SQL'
    POSTGRES = 'PGS'

    TYPE = [
        (ORACLE, 'Oracle'),
        (SQLSERVER, 'SQLServer'),
        (POSTGRES, 'PostgreSQL'),
    ]

database/models/database/__init__.py
"""Database base models"""

from django.db import models
from django.urls import reverse

from core.models import Metric, Snapshot
from database.models import DatabaseType
from database.models.instance import Instance


class DatabaseReplicationSystem(models.Model):
    """Database repliacation system model"""

    name = models.CharField('Name', max_length=9)
    system_id = models.CharField('Unique replication system identifier', max_length=64)

    class Meta:
        db_table = 'database_database_replication_system'
        constraints = [
            models.UniqueConstraint(
                fields=['name', 'system_id'], name='databasereplicationsystem_set_unique')
        ]


# pylint: disable=R0903
class DatabaseManager(models.Manager):
    """Database manager"""

    def search(self, query=None):
        """Search for database"""

        qs = self.get_queryset()
        if query is not None:
            or_lookup = (
                models.Q(name__icontains=query)
            )
            # distinct() is often necessary with Q lookups
            qs = qs.filter(or_lookup).order_by('name')
        return qs


class Database(models.Model):
    """Base database model"""

    name = models.CharField('Name of this database', max_length=128)
    type = models.CharField(max_length=3, choices=DatabaseType.TYPE)
    cluster_id = models.CharField('Unique cluster identifier', max_length=64)

    instances = models.ManyToManyField(Instance)
    snapshot = models.ForeignKey(Snapshot, on_delete=models.CASCADE)

    objects = DatabaseManager()

    class Meta:
        db_table = 'database_database'
        ordering = ['name']
        constraints = [
            models.UniqueConstraint(
                fields=['name', 'cluster_id'], name='database_set_unique')
        ]

    def __str__(self):
        """Return string representation"""
        return f"{self.name} ({self.get_type_display()})"

    def get_absolute_url(self):
        """Return object absolute url"""

        if self.type == DatabaseType.ORACLE:
            return self.oracledatabase.get_absolute_url()  # pylint: disable=no-member

        return reverse('database:database-detail', kwargs={'pk': self.pk})

    def get_sites(self):
        """Return the site of servers hosting this database"""

        sites = []
        for instance in self.instances.all().select_related("server"):
            if instance.server.site not in sites:
                sites.append(instance.server.site)

        return sites

    def get_host(self):
        """Return a tuple of host type and host name"""

        server = self.instances.first().server

        # Don't want the FQDN, so split on "." and return first element
        if server.cluster:
            return ("cluster", server.cluster.name.split('.')[0])

        return ("cluster", server.name.split('.')[0])


class DatabaseSizeMetric(Metric):
    """Database size metric"""

    database = models.ForeignKey(Database, on_delete=models.CASCADE)
    size = models.PositiveBigIntegerField('Total database size')
    datafile_size = models.PositiveBigIntegerField('Datafiles size')
    redo_size = models.PositiveBigIntegerField('Redo size')
    tempfile_size = models.PositiveBigIntegerField('Tempfiles size')


    class Meta(Metric.Meta):
        db_table = 'database_database_size_metric'

database/models/diskgroup/__init__.py
from django.db import models

from core.models import Metric
from database.models.instance import Instance

class DiskgroupParameterMetric(Metric):
    """Diskgroup parameter metric model"""

    instance = models.ForeignKey(Instance, on_delete=models.CASCADE)
    name = models.CharField('Name', max_length=80)
    value = models.TextField('Value')

    class Meta(Metric.Meta):
        db_table = 'database_diskgroup_parameter_metric'
        ordering = ['name']

database/models/engine/__init__.py
from django.db import models
from django.urls import reverse

from system.models import Server

class Engine(models.Model):
    """Instance binary model"""

    path = models.CharField('Instance\'s binary', max_length=255)
    server = models.ForeignKey(Server, on_delete=models.CASCADE)
    version = models.CharField('Version', max_length=255)

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['path', 'server'], name='engine_set_unique')
        ]


    def __str__(self):
        return f"{self.path}"


    def get_absolute_url(self):
        """Return object absolute url"""

        return reverse('database:instancebinary-detail', kwargs={'pk': self.pk})

database/models/instance/__init__.py
"""Instance base models"""

from django.db import models
from django.urls import reverse

from core.models import Environment, Metric, Snapshot, Vendor
from database.models import DatabaseType
from database.models.engine import Engine
from system.models import Server


# pylint: disable=R0903
class InstanceManager(models.Manager):
    """Instance manager"""

    def search(self, query=None):
        """Search for instance"""

        qs = self.get_queryset()
        if query is not None:
            or_lookup = models.Q(name__icontains=query)
            # distinct() is often necessary with Q lookups
            qs = qs.filter(or_lookup).distinct()
        return qs


class Instance(models.Model):
    """Base instance model"""

    name = models.CharField('Name', max_length=255)
    type = models.CharField(max_length=3, choices=DatabaseType.TYPE)

    server = models.ForeignKey(Server, on_delete=models.CASCADE)
    vendor = models.ForeignKey(Vendor, on_delete=models.CASCADE)
    engine = models.ForeignKey(Engine, on_delete=models.CASCADE)
    snapshot = models.ForeignKey(Snapshot, on_delete=models.CASCADE)
    environment = models.ForeignKey(Environment, on_delete=models.CASCADE, blank=True, null=True)

    objects = InstanceManager()

    class Meta:
        db_table = 'database_instance'
        ordering = ['name']
        constraints = [
            models.UniqueConstraint(
                fields=['name', 'server'], name='instance_set_unique')
        ]

    def __str__(self):
        """Return string representation"""
        return f"{self.name} ({self.get_type_display()})"

    def get_absolute_url(self):
        """Return object absolute url"""

        if self.type == DatabaseType.ORACLE:
            return self.oracleinstance.get_absolute_url()  # pylint: disable=no-member

        return reverse('database:instance-detail', kwargs={'pk': self.pk})


class InstanceParameterMetric(Metric):
    """Instance parameter metric model"""

    instance = models.ForeignKey(Instance, on_delete=models.CASCADE)
    name = models.CharField('Name', max_length=80)
    value = models.TextField('Value')

    class Meta(Metric.Meta):
        db_table = 'database_instance_parameter_metric'
        ordering = ['name']

database/models/tablespace/__init__.py
"""Tablespace base models"""

from django.db import models
from django.urls import reverse

from core.models import Metric, Snapshot
from database.models import DatabaseType
from database.models.database import Database


# pylint: disable=R0903
class TablespaceManager(models.Manager):
    """Tablepsace manager"""

    def search(self, query=None):
        """Search for tablespace"""

        qs = self.get_queryset()
        if query is not None:
            or_lookup = (
                models.Q(name__icontains=query)
            )
            # distinct() is often necessary with Q lookups
            qs = qs.filter(or_lookup).order_by('name')
        return qs


class Tablespace(models.Model):
    """Tablespace model"""

    name = models.CharField('Name', max_length=30)
    type = models.CharField(max_length=3, choices=DatabaseType.TYPE)

    database = models.ForeignKey(Database, on_delete=models.CASCADE)
    snapshot = models.ForeignKey(Snapshot, on_delete=models.CASCADE)

    objects = TablespaceManager()

    class Meta:
        db_table = 'database_tablespace'
        ordering = ['name']
        constraints = [
            models.UniqueConstraint(
                fields=['name', 'database'], name='tablespace_set_unique')
        ]

    def __str__(self):
        return f"{self.name}"

    def get_absolute_url(self):
        """Return object absolute url"""

        if self.type == DatabaseType.ORACLE:
            return self.oracletablespace.get_absolute_url()  # pylint: disable=no-member


class TablespaceSpaceMetric(Metric):
    """Tablespace space metric"""

    tablespace = models.ForeignKey(Tablespace, on_delete=models.CASCADE)
    size = models.PositiveBigIntegerField('Size')
    used = models.PositiveBigIntegerField('Used')
    max_size = models.PositiveBigIntegerField('Max Size')

    class Meta(Metric.Meta):
        db_table = 'database_tablespace_space_metric'

database/models/tns/__init__.py
"""Tns base models"""

from django.db import models
from django.urls import reverse
from database.models.database import Database
from database.models.engine import Engine

from system.models import Cluster, Server

# class Listener(models.Model):
#     """Listener model"""

#     name = models.CharField('Name', max_length=30)
#     type = models.CharField(max_length=3, choices=DatabaseType.TYPE)
#     engine = models.ForeignKey(Engine, on_delete=models.CASCADE)

#     class Meta:
#         db_table = 'database_listener'
#         ordering = ['name']

#     def __str__(self):
#         """Return string representation"""
#         return f"{self.name}"

#     def get_absolute_url(self):
#         """Return object absolute url"""

#         if self.type == DatabaseType.ORACLE:
#             return self.oraclelistener.get_absolute_url()  # pylint: disable=no-member

class Listener(models.Model):
    """Listener model"""

    LOCAL = 'LOCAL'
    SCAN = 'SCAN'

    ORACLE_LISTENER_TYPE = [
        (LOCAL, 'Local Listener'),
        (SCAN, 'Scan Listener'),
    ]

    name = models.CharField('Name', max_length=30)
    type = models.CharField(max_length=5, choices=ORACLE_LISTENER_TYPE)
    engine = models.ForeignKey(Engine, on_delete=models.CASCADE)

    class Meta:
        db_table = 'database_listener'

    def __str__(self):
        """Return string representation"""
        return f"{self.name}"

    def get_absolute_url(self):
        """Return object absolute url"""

        if self.type == self.LOCAL:
            return self.locallistener.get_absolute_url()  # pylint: disable=no-member
        else:
            return self.scanlistener.get_absolute_url()  # pylint: disable=no-member


class LocalListener(Listener):
    """LocalListener model"""

    server = models.ForeignKey(Server, on_delete=models.CASCADE)

    class Meta:
        db_table = 'database_listener_local'

    def save(self, *args, **kwargs):
        self.type = Listener.LOCAL
        super().save(*args, **kwargs)

    def __str__(self):
        """Return string representation"""
        return f"{self.name} (Local Listener)"

    def get_absolute_url(self):
        """Return object absolute url"""
        return reverse('database:listener-local-detail', kwargs={'pk': self.pk})


class ScanListener(Listener):
    """ScanListener model"""

    cluster = models.ForeignKey(Cluster, on_delete=models.CASCADE)

    class Meta:
        db_table = 'database_listener_scan'

    def save(self, *args, **kwargs):
        self.type = Listener.SCAN
        super().save(*args, **kwargs)

    def __str__(self):
        """Return string representation"""
        return f"{self.name} (SCAN Listener)"

    def get_absolute_url(self):
        """Return object absolute url"""
        return reverse('database:listener-scan-detail', kwargs={'pk': self.pk})


class Endpoint(models.Model):
    """Endpoint model"""

    hostname = models.CharField('Hostname', max_length=255)
    port = models.PositiveSmallIntegerField('Port')

    listener = models.ForeignKey(Listener, on_delete=models.CASCADE)

    class Meta:
        db_table = 'database_endpoint'


# pylint: disable=R0903
class ServiceManager(models.Manager):
    """Service manager"""

    def search(self, query=None):
        """Search for service"""

        qs = self.get_queryset()
        if query is not None:
            or_lookup = (
                models.Q(name__icontains=query)
            )
            # distinct() is often necessary with Q lookups
            qs = qs.filter(or_lookup).order_by('name')
        return qs


class Service(models.Model):
    """Service Model"""

    name = models.CharField('Name', max_length=512)

    listeners = models.ManyToManyField(Listener)
    database = models.ForeignKey(Database, on_delete=models.CASCADE)

    objects = ServiceManager()

    class Meta:
        db_table = 'database_service'

    def __str__(self):
        """Return string representation"""
        return f"{self.name}"

    def get_absolute_url(self):
        """Return object absolute url"""
        return reverse('database:service-detail', kwargs={'pk': self.pk})

database/models/user/__init__.py
from django.db import models
from django.urls import reverse

from core.models import Metric, Snapshot
from database.models import DatabaseType
from database.models.database import Database


# pylint: disable=R0903
class UserManager(models.Manager):
    """User manager"""

    def search(self, query=None):
        """Search for user"""

        qs = self.get_queryset()
        if query is not None:
            or_lookup = (
                models.Q(name__icontains=query)
            )
            # distinct() is often necessary with Q lookups
            qs = qs.filter(or_lookup).distinct()
        return qs


class User(models.Model):
    """User model"""

    name = models.CharField('Username', max_length=128)
    type = models.CharField(max_length=3, choices=DatabaseType.TYPE)

    database = models.ForeignKey(Database, on_delete=models.CASCADE)
    snapshot = models.ForeignKey(Snapshot, on_delete=models.CASCADE)

    objects = UserManager()

    class Meta:
        db_table = 'database_user'
        ordering = ['name']
        constraints = [
            models.UniqueConstraint(
                fields=['database', 'name'], name='user_set_unique')
        ]

    def __str__(self):
        return f"{self.name}"

    def get_absolute_url(self):
        """Return object absolute url"""

        if self.type == DatabaseType.ORACLE:
            return self.oracleuser.get_absolute_url()


class UserSpaceMetric(Metric):
    """Tablespace space metric"""

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    size = models.PositiveBigIntegerField('Size')

    class Meta(Metric.Meta):
        db_table = 'database_user_space_metric'

database/templates/database/database.html
{% extends "core/skeleton.html" %}

{% block breadcrumb %}
{{ block.super }}
<li class="breadcrumb-item"><a href="{% url 'database:database-list' %}">Databases</a></li>
{% endblock %}

database/templates/database/database_detail.html
{% extends "database/database.html" %}
{% load mathfilters %}

{% block breadcrumb %}
{{ block.super }}
<li class="breadcrumb-item">{{ object.name }}</li>
{% endblock %}

{% block content %}
<table class="table">
    <tbody>
        <tr>
            <th>Name</th>
            <td><a href="{{ database.get_absolute_url }}">{{ object }}</a></td>
        </tr>
        <tr>
            <th>Type</th>
            <td>{{ object.get_type_display }}</td>
        </tr>
        <tr>
            <th>Snapshot date</th>
            <td><!-- Snapshot ID : {{ object.snapshot.id }} -->{{ object.snapshot.date }}</td>
        </tr>
    </tbody>
</table>

<ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
    <li class="nav-item" role="presentation">
        <button class="nav-link active" id="pills-instances-tab" data-bs-toggle="pill" data-bs-target="#pills-instances" type="button" role="tab" aria-controls="pills-instances" aria-selected="true">Instances</button>
    </li>
</ul>
<div class="tab-content" id="pills-tabContent">
    <div class="tab-pane fade show active" id="pills-instances" role="tabpanel" aria-labelledby="pills-instances-tab" tabindex="0">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Instance</th>
                    <th>Server</th>
                </tr>
            </thead>
            <tbody class="table-group-divider">
                {% for instance in object.instances.all %}
                <tr>
                    <td><a href="{{ instance.get_absolute_url }}">{{ instance }}</a></td>
                    <td><a href="{{ instance.server.get_absolute_url }}">{{ instance.server }}</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

database/templates/database/database_list.html
{% extends "database/database.html" %}

{% block content %}

{% include "core/paginator.html" %}
<a href="{% url 'database:database-export' %}"><i class="bi-filetype-csv" style="font-size: 2rem;"></i></a>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Name ({{ paginator.count }})</th>
        </tr>
    </thead>
    <tbody class="table-group-divider">
        {% for database in object_list %}
        <tr>
            <td><a href="{{ database.get_absolute_url }}">{{ database }}</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% include "core/paginator.html" %}

{% endblock %}

database/templates/database/diskgroup.html
{% extends "core/skeleton.html" %}

{% block breadcrumb %}
{{ block.super }}
<li class="breadcrumb-item">Diskgroup</li>
{% endblock %}

database/templates/database/instance.html
{% extends "core/skeleton.html" %}

{% block breadcrumb %}
{{ block.super }}
<li class="breadcrumb-item"><a href="{% url 'database:instance-list' %}">Instances</a></li>
{% endblock %}

database/templates/database/instancebinary_detail.html
{% extends "database/instance.html" %}

{% block breadcrumb %}
{{ block.super }}
<li class="breadcrumb-item">{{ instancebinary.path }}</li>
{% endblock %}

{% block content %}
<table class="table">
    <tbody>
        <tr>
            <th>Path</th>
            <td>{{ instancebinary.path }}</td>
        </tr>
        <tr>
            <th>Server</th>
            <td><a href="{{ instancebinary.server.get_absolute_url }}">{{ instancebinary.server }}</a></td>
        </tr>
    </tbody>
</table>

<ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
    <li class="nav-item" role="presentation">
        <button class="nav-link active" id="pills-home-tab" data-bs-toggle="pill" data-bs-target="#pills-home" type="button" role="tab" aria-controls="pills-home" aria-selected="true">Instances</button>
    </li>
</ul>
<div class="tab-content" id="pills-tabContent">
    <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab" tabindex="0">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Name</th>
                </tr>
            </thead>
            <tbody class="table-group-divider">
                {% for instance in instancebinary.instance_set.all %}
                <tr>
                    <td><a href="{{ instance.get_absolute_url }}">{{ instance }}</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

database/templates/database/listener.html
{% extends "core/skeleton.html" %}

{% block breadcrumb %}
{{ block.super }}
<li class="breadcrumb-item">Listeners</li>
{% endblock %}

database/templates/database/listener_scan_detail.html
{% extends "database/listener.html" %}

{% block breadcrumb %}
{{ block.super }}
<li class="breadcrumb-item">{{ object }}</li>
{% endblock %}

{% block content %}
<table class="table">
    <tbody>
        <tr>
            <th>Name</th>
            <td>{{ object }}</td>
        </tr>
        <tr>
            <th>Cluster</th>
            <td><a href="{{ object.cluster.get_absolute_url }}">{{ object.cluster }}</a></td>
        </tr>
        <tr>
            <th>Endpoints</th>
            <td>
                {% for endpoint in object.endpoint_set.all %}
                {{ endpoint.hostname }}:{{ endpoint.port }}<br />
                {% endfor %}
            </td>
        </tr>
    </tbody>
</table>

<ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
    <li class="nav-item" role="presentation">
        <button class="nav-link active" id="pills-services-tab" data-bs-toggle="pill" data-bs-target="#pills-services" type="button" role="tab" aria-controls="pills-services" aria-selected="true">Services</button>
    </li>
</ul>
<div class="tab-content" id="pills-tabContent">
    <div class="tab-pane fade show active" id="pills-services" role="tabpanel" aria-labelledby="pills-services-tab" tabindex="0">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Name</th>
                </tr>
            </thead>
            <tbody class="table-group-divider">
                {% for service in object.service_set.all %}
                <tr>
                    <td><a href="{{ service.get_absolute_url }}">{{ service }}</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

database/templates/database/service.html
{% extends "core/skeleton.html" %}

{% block breadcrumb %}
{{ block.super }}
<li class="breadcrumb-item">Services</li>
{% endblock %}

database/templates/database/service_detail.html
{% extends "database/service.html" %}

{% block breadcrumb %}
{{ block.super }}
<li class="breadcrumb-item">{{ object }}</li>
{% endblock %}

{% block content %}
<table class="table">
    <tbody>
        <tr>
            <th>Name</th>
            <td>{{ object }}</td>
        </tr>
        <tr>
            <th>Target Database</th>
            <td><a href="{{ object.database.get_absolute_url }}">{{ object.database }}</a></td>
        </tr>
    </tbody>
</table>

<ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
    <li class="nav-item" role="presentation">
        <button class="nav-link active" id="pills-listeners-tab" data-bs-toggle="pill" data-bs-target="#pills-listeners" type="button" role="tab" aria-controls="pills-listeners" aria-selected="true">Listeners</button>
    </li>
</ul>
<div class="tab-content" id="pills-tabContent">
    <div class="tab-pane fade show active" id="pills-listeners" role="tabpanel" aria-labelledby="pills-listeners-tab" tabindex="0">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Name</th>
                </tr>
            </thead>
            <tbody class="table-group-divider">
                {% for listener in object.listeners.all %}
                <tr>
                    <td><a href="{{ listener.get_absolute_url }}">{{ listener }}</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

database/templates/database/tablespace_detail.html
{% extends "database/tablespace.html" %}

{% block breadcrumb %}
{{ block.super }}
<li class="breadcrumb-item">{{ object.name }}</li>
{% endblock %}

{% block content %}
<table class="table">
    <tbody>
        <tr>
            <th>Name</th>
            <td>{{ object.name }}</td>
        </tr>
        <tr>
            <th>Database</th>
            <td><a href="{{ object.database.get_absolute_url }}">{{ object.database }}</a></td>
        </tr>
        <tr>
            <th>Bigfile</th>
            <td>{{ object.bigfile }}</td>
        </tr>
        <tr>
            <th>Block Size</th>
            <td>{{ object.block_size }}</td>
        </tr>
        <tr>
            <th>Extent Management</th>
            <td>{{ object.extent_management }}</td>
        </tr>
        <tr>
            <th>Force Logging</th>
            <td>{{ object.force_logging }}</td>
        </tr>
        <tr>
            <th>Segment Space Management</th>
            <td>{{ object.segment_space_management }}</td>
        </tr>
        <tr>
            <th>Contents</th>
            <td>{{ object.contents }}</td>
        </tr>
        <tr>
            <th>Snapshot date</th>
            <td><!-- Snapshot ID : {{ object.snapshot.id }} -->{{ object.snapshot.date }}</td>
        </tr>
    </tbody>
</table>
<div>
    <canvas id="weeklyHistory"></canvas>
</div>
{% endblock %}

{% block js_file %}
{{ block.super }}
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chartjs-adapter-date-fns/dist/chartjs-adapter-date-fns.bundle.min.js"></script>
{% endblock %}

{% block js_script %}
{{ block.super }}
<script>
    document.addEventListener("DOMContentLoaded", function () {
        const weeklyHistoryChartEl = document.getElementById("weeklyHistory").getContext("2d");
        const data = {
            "datasets":[
                {
                    "data":[
                        {% for metric in tablespace.tablespacespacemetric_set.all %}
                        {
                        "x":'{{metric.date | date:"Y-m-d H:i:s"}}',
                        "y":{{metric.used}}
                        },{% endfor %}
                    ],
                    "label":"Used"
                },
            ]
        };
        var weeklyHistoryChart = new Chart(weeklyHistoryChartEl, {
            type: "line",
            data: data,
            options: {
                spanGaps: true,
                scales: {
                    x: {
                        type: "time",
                    }
                }
            }
        });
    });
</script>
{% endblock %}

database/templates/database/tablespace_list.html
{% extends "database/tablespace.html" %}

{% block content %}

{% include "core/paginator.html" %}
<a href="{% url 'database:tablespace-export' %}"><i class="bi-filetype-csv" style="font-size: 2rem;"></i></a>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Name ({{ paginator.count }})</th>
            <th>Database</th>
        </tr>
    </thead>
    <tbody class="table-group-divider">
        {% for tablespace in object_list %}
        <tr>
            <td><a href="{{ tablespace.get_absolute_url }}">{{ tablespace }}</a></td>
            <td><a href="{{ tablespace.database.get_absolute_url }}">{{ tablespace.database }}</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% include "core/paginator.html" %}

{% endblock %}

database/templates/database/user_detail.html
{% extends "database/user.html" %}

{% block breadcrumb %}
{{ block.super }}
<li class="breadcrumb-item">{{ object }}</li>
{% endblock %}

{% block content %}
<table class="table">
    <tbody>
        <tr>
            <th>Name</th>
            <td>{{ object }}</td>
        </tr>
        <tr>
            <th>Database</th>
            <td><a href="{{ object.database.get_absolute_url }}">{{ object.database }}</a></td>
        </tr>
        <tr>
            <th>Account status</th>
            <td>{{ object.account_status }}</td>
        </tr>
        <tr>
            <th>Lock date</th>
            <td>{{ object.lock_date }}</td>
        </tr>
        <tr>
            <th>Expiry date</th>
            <td>{{ object.expiry_date }}</td>
        </tr>
        <tr>
            <th>Default tablespace</th>
            <td>{{ object.default_tablespace }}</td>
        </tr>
        <tr>
            <th>Temporary tablespace</th>
            <td>{{ object.temporary_tablespace }}</td>
        </tr>
        <tr>
            <th>Created</th>
            <td>{{ object.created }}</td>
        </tr>
        <tr>
            <th>Profile</th>
            <td>{{ object.profile }}</td>
        </tr>
        <tr>
            <th>Last login</th>
            <td>{{ object.last_login }}</td>
        </tr>
        <tr>
            <th>Password versions</th>
            <td>{{ object.password_versions }}</td>
        </tr>
        <tr>
            <th>Authentication type</th>
            <td>{{ object.authentication_type }}</td>
        </tr>
        <tr>
            <th>Common</th>
            <td>{{ object.common }}</td>
        </tr>
        <tr>
            <th>Password change date</th>
            <td>{{ object.password_change_date }}</td>
        </tr>
        <tr>
            <th>Snapshot date</th>
            <td><!-- Snapshot ID : {{ object.snapshot.id }} -->{{ object.snapshot.date }}</td>
        </tr>
    </tbody>
</table>
{% endblock %}

database/templates/database/user_list.html
{% extends "database/user.html" %}

{% block content %}

{% include "core/paginator.html" %}
<a href="{% url 'database:user-export' %}"><i class="bi-filetype-csv" style="font-size: 2rem;"></i></a>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Name ({{ paginator.count }})</th>
            <th>Database</th>
        </tr>
    </thead>
    <tbody class="table-group-divider">
        {% for object in object_list %}
        <tr>
            <td><a href="{{ object.get_absolute_url }}">{{ object }}</a></td>
            <td><a href="{{ object.database.get_absolute_url }}">{{ object.database }}</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% include "core/paginator.html" %}

{% endblock %}